#[workspace]

[package]
name = "rust-wasm-modplayer"
version = "1.0.0"
edition = "2018"


[dependencies]
crossbeam = "0.8.4"
xmplayer = {path="../xmplayer"}
display = {path="../display"}
lazy_static = "1.4.0"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]