#[workspace]

[package]
name = "modplayer-wasm"
version = "1.0.0"
edition = "2018"

[dependencies]
xmplayer = {path="../xmplayer"}
wasm-bindgen = { version = "0.2.100" }
js-sys = "0.3.77"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[lib]
crate-type = ["cdylib", "rlib"]
